{% set name = "npysearch" %}
{% set version = "1.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/npysearch-{{ version }}.tar.gz
  sha256: 03c4b7a3be80f5168e6df3f9dc57cdca71d822f09a3a5d90994c308334a53f46

build:
  number: 1
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - pybind11
    - python
  run:
    - python

test:
  imports:
    - npysearch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jeevannavar/npysearch
  summary: Python bindings for nsearch, an efficient BLAST-like sequence comparison algorithm written in C++
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeevannavar
    - manutamminen
